// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateJob(arg1:model.CreateJobParams):Promise<model.Job>;

export function CreateRecord(arg1:model.CreateRecordParams):Promise<model.Record>;

export function DeleteJob(arg1:number):Promise<void>;

export function FindJobs():Promise<Array<model.Job>>;

export function OnResizeWindow():Promise<void>;

export function UpdateJob(arg1:model.UpdateJobParams):Promise<model.Job>;
