// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function FindJobs() {
  return window['go']['main']['App']['FindJobs']();
}

export function OnResizeWindow() {
  return window['go']['main']['App']['OnResizeWindow']();
}

export function UpdateJob(arg1) {
  return window['go']['main']['App']['UpdateJob'](arg1);
}
