// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function FindJobs() {
  return window['go']['main']['App']['FindJobs']();
}
